name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Apt Get Update
        run: sudo apt-get update
      - name: Install Protobuf Compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Format
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets --locked -- -D warnings
      - name: Build
        run: cargo build --workspace --all-targets --locked
      - name: Test
        run: cargo test --workspace --locked
